### ISSUE TITLE
TypeError: __new__() got an unexpected keyword argument 'code'

### ISSUE THREAD

**Issue by silverwind** [SublimeLinter/SublimeLinter-stylelint#15]
Trying to run this linter plugin, I get this error (and no highlights):
````
SublimeLinter: ERROR: Unhandled exception:
Traceback (most recent call last):
  File "SublimeLinter.sublime-package\lint/backend.py", line 111, in execute_lint_task
    errors = linter.lint(code, view_has_changed) or []
  File "SublimeLinter.sublime-package\lint/linter.py", line 925, in lint
    return self.parse_output(output, virtual_view)
  File "SublimeLinter.sublime-package\lint/linter.py", line 946, in parse_output
    return self.parse_output_via_regex(output, virtual_view)
  File "SublimeLinter.sublime-package\lint/linter.py", line 958, in parse_output_via_regex
    for m in self.find_errors(output):
  File "SublimeLinter-stylelint.sublime-package\linter.py", line 70, in find_errors
    message=text
TypeError: __new__() got an unexpected keyword argument 'code'
````

Not sure what's the issue, but manually running stylelint works:

````
$ npx stylelint src/css/*.scss

src/css/style.scss
 463:3  ✖  Invalid value for `transition-duration`   csstree/validator
````

Stylelint config is https://github.com/silverwind/eslint-config-silverwind

**Comment by silverwind** [comment]
Actually, reinstalling SublimeLinter fixed this, so it was probably out of date, sorry for the noise.

**Comment by idealatom** [comment]
I also have this problem. Already tried to reinstall SublimeLinter and SublimeLinter-stylelint, but it's didn't help.

```
SublimeLinter: #336 linter.py:987     stylelint: output:
  [{"source":"/home/idealatom/projects/3dplitka/plitka/static/css/cards.css","deprecations":[],"invalidOptionWarnings":[],"parseErrors":[],"errored":true,"warnings":[{"line":132,"column":20,"rule":"block-no-empty","severity":"error","text":"Unexpected empty block (block-no-empty)"},{"line":30,"column":15,"rule":"block-opening-brace-space-before","severity":"error","text":"Expected single space before \"{\" (block-opening-brace-space-before)"},{"line":28,"column":19,"rule":"color-hex-case","severity":"error","text":"Expected \"#B5B5B5\" to be \"#b5b5b5\" (color-hex-case)"},{"line":97,"column":23,"rule":"color-hex-case","severity":"error","text":"Expected \"#D7FFD7\" to be \"#d7ffd7\" (color-hex-case)"},{"line":173,"column":12,"rule":"color-hex-case","severity":"error","text":"Expected \"#00A9D4\" to be \"#00a9d4\" (color-hex-case)"},{"line":178,"column":12,"rule":"color-hex-case","severity":"error","text":"Expected \"#00A9D4\" to be \"#00a9d4\" (color-hex-case)"},{"line":193,"column":12,"rule":"color-hex-case","severity":"error","text":"Expected \"#00A9D4\" to be \"#00a9d4\" (color-hex-case)"},{"line":47,"column":12,"rule":"color-hex-length","severity":"error","text":"Expected \"#cc0000\" to be \"#c00\" (color-hex-length)"},{"line":2,"column":9,"rule":"comment-empty-line-before","severity":"error","text":"Expected empty line before comment (comment-empty-line-before)"},{"line":3,"column":1,"rule":"comment-empty-line-before","severity":"error","text":"Expected empty line before comment (comment-empty-line-before)"},{"line":10,"column":1,"rule":"comment-empty-line-before","severity":"error","text":"Expected empty line before comment (comment-empty-line-before)"},{"line":11,"column":1,"rule":"comment-empty-line-before","severity":"error","text":"Expected empty line before comment (comment-empty-line-before)"},{"line":55,"column":1,"rule":"comment-empty-line-before","severity":"error","text":"Expected empty line before comment (comment-empty-line-before)"},{"line":61,"column":1,"rule":"comment-empty-line-before","severity":"error","text":"Expected empty line before comment (comment-empty-line-before)"},{"line":77,"column":5,"rule":"comment-empty-line-before","severity":"error","text":"Expected empty line before comment (comment-empty-line-before)"},{"line":82,"column":5,"rule":"comment-empty-line-before","severity":"error","text":"Expected empty line before comment (comment-empty-line-before)"},{"line":10,"column":3,"rule":"comment-whitespace-inside","severity":"error","text":"Expected whitespace after \"/*\" (comment-whitespace-inside)"},{"line":10,"column":56,"rule":"comment-whitespace-inside","severity":"error","text":"Expected whitespace before \"*/\" (comment-whitespace-inside)"},{"line":11,"column":3,"rule":"comment-whitespace-inside","severity":"error","text":"Expected whitespace after \"/*\" (comment-whitespace-inside)"},{"line":66,"column":1,"rule":"comment-whitespace-inside","severity":"error","text":"Expected whitespace before \"*/\" (comment-whitespace-inside)"},{"line":77,"column":7,"rule":"comment-whitespace-inside","severity":"error","text":"Expected whitespace after \"/*\" (comment-whitespace-inside)"},{"line":77,"column":24,"rule":"comment-whitespace-inside","severity":"error","text":"Expected whitespace before \"*/\" (comment-whitespace-inside)"},{"line":82,"column":7,"rule":"comment-whitespace-inside","severity":"error","text":"Expected whitespace after \"/*\" (comment-whitespace-inside)"},{"line":82,"column":26,"rule":"comment-whitespace-inside","severity":"error","text":"Expected whitespace before \"*/\" (comment-whitespace-inside)"},{"line":150,"column":47,"rule":"function-comma-space-after","severity":"error","text":"Expected single space after \",\" in a single-line function (function-comma-space-after)"},{"line":150,"column":49,"rule":"function-comma-space-after","severity":"error","text":"Expected single space after \",\" in a single-line function (function-comma-space-after)"},{"line":150,"column":51,"rule":"function-comma-space-after","severity":"error","text":"Expected single space after \",\" in a single-line function (function-comma-space-after)"},{"line":151,"column":44,"rule":"function-comma-space-after","severity":"error","text":"Expected single space after \",\" in a single-line function (function-comma-space-after)"},{"line":151,"column":46,"rule":"function-comma-space-after","severity":"error","text":"Expected single space after \",\" in a single-line function (function-comma-space-after)"},{"line":151,"column":48,"rule":"function-comma-space-after","severity":"error","text":"Expected single space after \",\" in a single-line function (function-comma-space-after)"},{"line":152,"column":39,"rule":"function-comma-space-after","severity":"error","text":"Expected single space after \",\" in a single-line function (function-comma-space-after)"},{"line":152,"column":41,"rule":"function-comma-space-after","severity":"error","text":"Expected single space after \",\" in a single-line function (function-comma-space-after)"},{"line":152,"column":43,"rule":"function-comma-space-after","severity":"error","text":"Expected single space after \",\" in a single-line function (function-comma-space-after)"},{"line":150,"column":38,"rule":"length-zero-no-unit","severity":"error","text":"Unexpected unit (length-zero-no-unit)"},{"line":151,"column":35,"rule":"length-zero-no-unit","severity":"error","text":"Unexpected unit (length-zero-no-unit)"},{"line":152,"column":30,"rule":"length-zero-no-unit","severity":"error","text":"Unexpected unit (length-zero-no-unit)"},{"line":200,"column":1,"rule":"max-empty-lines","severity":"error","text":"Expected no more than 1 empty line (max-empty-lines)"},{"line":212,"column":1,"rule":"max-empty-lines","severity":"error","text":"Expected no more than 1 empty line (max-empty-lines)"},{"line":181,"column":1,"rule":"no-descending-specificity","severity":"error","text":"Expected selector \"a.category-link\" to come before selector \"a.category-link:hover\" (no-descending-specificity)"},{"line":27,"column":1,"rule":"rule-empty-line-before","severity":"error","text":"Expected empty line before rule (rule-empty-line-before)"},{"line":30,"column":1,"rule":"rule-empty-line-before","severity":"error","text":"Expected empty line before rule (rule-empty-line-before)"},{"line":34,"column":1,"rule":"rule-empty-line-before","severity":"error","text":"Expected empty line before rule (rule-empty-line-before)"},{"line":41,"column":1,"rule":"rule-empty-line-before","severity":"error","text":"Expected empty line before rule (rule-empty-line-before)"},{"line":45,"column":1,"rule":"rule-empty-line-before","severity":"error","text":"Expected empty line before rule (rule-empty-line-before)"},{"line":49,"column":1,"rule":"rule-empty-line-before","severity":"error","text":"Expected empty line before rule (rule-empty-line-before)"},{"line":53,"column":1,"rule":"rule-empty-line-before","severity":"error","text":"Expected empty line before rule (rule-empty-line-before)"},{"line":74,"column":1,"rule":"rule-empty-line-before","severity":"error","text":"Expected empty line before rule (rule-empty-line-before)"},{"line":85,"column":1,"rule":"rule-empty-line-before","severity":"error","text":"Expected empty line before rule (rule-empty-line-before)"},{"line":101,"column":1,"rule":"rule-empty-line-before","severity":"error","text":"Expected empty line before rule (rule-empty-line-before)"},{"line":129,"column":1,"rule":"rule-empty-line-before","severity":"error","text":"Expected empty line before rule (rule-empty-line-before)"},{"line":132,"column":1,"rule":"rule-empty-line-before","severity":"error","text":"Expected empty line before rule (rule-empty-line-before)"},{"line":146,"column":1,"rule":"rule-empty-line-before","severity":"error","text":"Expected empty line before rule (rule-empty-line-before)"},{"line":154,"column":1,"rule":"rule-empty-line-before","severity":"error","text":"Expected empty line before rule (rule-empty-line-before)"},{"line":157,"column":1,"rule":"rule-empty-line-before","severity":"error","text":"Expected empty line before rule (rule-empty-line-before)"},{"line":160,"column":1,"rule":"rule-empty-line-before","severity":"error","text":"Expected empty line before rule (rule-empty-line-before)"},{"line":163,"column":1,"rule":"rule-empty-line-before","severity":"error","text":"Expected empty line before rule (rule-empty-line-before)"},{"line":166,"column":1,"rule":"rule-empty-line-before","severity":"error","text":"Expected empty line before rule (rule-empty-line-before)"},{"line":177,"column":1,"rule":"rule-empty-line-before","severity":"error","text":"Expected empty line before rule (rule-empty-line-before)"},{"line":181,"column":1,"rule":"rule-empty-line-before","severity":"error","text":"Expected empty line before rule (rule-empty-line-before)"},{"line":185,"column":1,"rule":"rule-empty-line-before","severity":"error","text":"Expected empty line before rule (rule-empty-line-before)"},{"line":188,"column":1,"rule":"rule-empty-line-before","severity":"error","text":"Expected empty line before rule (rule-empty-line-before)"},{"line":195,"column":1,"rule":"rule-empty-line-before","severity":"error","text":"Expected empty line before rule (rule-empty-line-before)"},{"line":204,"column":1,"rule":"rule-empty-line-before","severity":"error","text":"Expected empty line before rule (rule-empty-line-before)"},{"line":218,"column":1,"rule":"rule-empty-line-before","severity":"error","text":"Expected empty line before rule (rule-empty-line-before)"},{"line":226,"column":1,"rule":"rule-empty-line-before","severity":"error","text":"Expected empty line before rule (rule-empty-line-before)"},{"line":229,"column":1,"rule":"rule-empty-line-before","severity":"error","text":"Expected empty line before rule (rule-empty-line-before)"},{"line":172,"column":16,"rule":"selector-list-comma-newline-after","severity":"error","text":"Expected newline after \",\" (selector-list-comma-newline-after)"},{"line":177,"column":22,"rule":"selector-list-comma-newline-after","severity":"error","text":"Expected newline after \",\" (selector-list-comma-newline-after)"}]}]
SublimeLinter: #336 __init__.py:1273  ERROR: Unhandled exception:
Traceback (most recent call last):
  File "/home/idealatom/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package/lint/backend.py", line 111, in execute_lint_task
    errors = linter.lint(code, view_has_changed) or []
  File "/home/idealatom/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package/lint/linter.py", line 926, in lint
    return self.filter_errors(self.parse_output(output, virtual_view))
  File "/home/idealatom/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package/lint/linter.py", line 951, in filter_errors
    for error in errors
  File "/home/idealatom/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package/lint/linter.py", line 950, in <listcomp>
    error
  File "/home/idealatom/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package/lint/linter.py", line 989, in parse_output_via_regex
    for m in self.find_errors(output):
  File "/home/idealatom/.config/sublime-text-3/Installed Packages/SublimeLinter-stylelint.sublime-package/linter.py", line 70, in find_errors
    message=text
TypeError: __new__() got an unexpected keyword argument 'code'
SublimeLinter: sublime_linter.py:449  Linting 'cards.css' took 0.50s
'''

**Comment by braver** [comment]
@kaste any idea what might cause this?

**Comment by kaste** [comment]
SublimeLinter framework out of date.

**Comment by braver** [comment]
That's what I thought. @idealatom you really need to check your setup to see why your SublimeLinter (the main package) is out of date.

**Comment by idealatom** [comment]
It's very strange. Now after several removing and reinstalling of SublimeLinter the error is gone inspite of I already tried it before and it didn't help. But anyway, thanks for your reply.
