### ISSUE TITLE
Crashes when using processor

### ISSUE THREAD

**Issue by ersinakinci** [SublimeLinter/SublimeLinter-stylelint#7]
When using a processor in stylelint.config.js/.stylelintrc, the plugin crashes:

`stylelint.config.js`:
```
module.exports = {
  extends: [
    'stylelint-config-standard',
  ],
  processors: ['stylelint-processor-styled-components'],
};
```

SublimeText console error:

```
SublimeLinter: ERROR: Unhandled exception:
Traceback (most recent call last):
  File "/Users/ersin/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/backend.py", line 111, in execute_lint_task
    errors = linter.lint(code, view_has_changed) or []
  File "/Users/ersin/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/linter.py", line 925, in lint
    return self.parse_output(output, virtual_view)
  File "/Users/ersin/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/linter.py", line 946, in parse_output
    return self.parse_output_via_regex(output, virtual_view)
  File "/Users/ersin/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/linter.py", line 958, in parse_output_via_regex
    for m in self.find_errors(output):
  File "/Users/ersin/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter-stylelint.sublime-package/linter.py", line 63, in find_errors
    line = warning['line'] - self.line_col_base[0]
KeyError: 'line'
```

**Comment by kaste** [comment]
Hi :wave:,

a warning without a line, nice. You could enable debug mode, then look in the Sublime Console which command SublimeLinter here executes and what output it generates. 

If the plugin doesn't produce a line we need to decide if we throw away the error (ignore it) or if we should place it at the first line.

Maybe related https://github.com/styled-components/stylelint-processor-styled-components/issues/178  Reading that issue it seems the authors suggest using 

```
{
  "processors": ["stylelint-processor-styled-components"],
  "extends": [
    "stylelint-config-styled-components"
  ]
}
```

to disable some rules.

**Comment by chinesedfan** [comment]
`stylelint-processor-styled-components` v1.5.0 has just been released. There should not be a warning without a line.

**Comment by kaste** [comment]
Hey cool, thanks for your fix. 😍
